version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - AI_SERVICE_URL=http://ai_service:5000
    depends_on:
      - ai_service

  ai_service:
    build: ./ai_service
    ports:
      - "5000:5000"
    volumes:
      - ./ai_service/data:/app/data 